/* tslint:disable */
/* eslint-disable */
/**
 * @cats-cradles/email-service
 * An API for the email service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from './base';

/**
 *
 * @export
 * @interface UserAccountCreatedDto
 */
export interface UserAccountCreatedDto {
  /**
   * The email recipient
   * @type {string}
   * @memberof UserAccountCreatedDto
   */
  recipient: string;
  /**
   * The first name of the recipient
   * @type {string}
   * @memberof UserAccountCreatedDto
   */
  firstName: string;
}
/**
 *
 * @export
 * @interface UserForgottenPasswordResetDto
 */
export interface UserForgottenPasswordResetDto {
  /**
   * The email recipient
   * @type {string}
   * @memberof UserForgottenPasswordResetDto
   */
  recipient: string;
  /**
   * The username of the recipient
   * @type {string}
   * @memberof UserForgottenPasswordResetDto
   */
  username: string;
  /**
   * The link for the reset password
   * @type {string}
   * @memberof UserForgottenPasswordResetDto
   */
  link: string;
}

export const emailMessageControllerConvertKey = (
  action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
  userAccountCreatedDto: UserAccountCreatedDto,
  options: any = {},
) => {
  const localVarPath = `/email-message/user-account-created`;
  // use dummy base URL string because the URL constructor only accepts absolute URLs.
  const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
  const canSearch =
    true &&
    action !== undefined &&
    action !== null &&
    userAccountCreatedDto !== undefined &&
    userAccountCreatedDto !== null;
  return canSearch ? localVarUrlObj.toString() : null;
};
export const emailMessageControllerConvertUserForgottenPasswordResetKey = (
  action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
  userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
  options: any = {},
) => {
  const localVarPath = `/email-message/user-forgotten-password-reset`;
  // use dummy base URL string because the URL constructor only accepts absolute URLs.
  const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
  const canSearch =
    true &&
    action !== undefined &&
    action !== null &&
    userForgottenPasswordResetDto !== undefined &&
    userForgottenPasswordResetDto !== null;
  return canSearch ? localVarUrlObj.toString() : null;
};
export const emailMessageControllerStatsKey = (options: any = {}) => {
  const localVarPath = `/email-message/stats`;
  // use dummy base URL string because the URL constructor only accepts absolute URLs.
  const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
  const canSearch = true;
  return canSearch ? localVarUrlObj.toString() : null;
};

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserAccountCreatedDto} userAccountCreatedDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerConvert: async (
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userAccountCreatedDto: UserAccountCreatedDto,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'action' is not null or undefined
      assertParamExists('emailMessageControllerConvert', 'action', action);
      // verify required parameter 'userAccountCreatedDto' is not null or undefined
      assertParamExists(
        'emailMessageControllerConvert',
        'userAccountCreatedDto',
        userAccountCreatedDto,
      );
      const localVarPath = `/email-message/user-account-created`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (action !== undefined) {
        localVarQueryParameter['action'] = action;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userAccountCreatedDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserForgottenPasswordResetDto} userForgottenPasswordResetDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerConvertUserForgottenPasswordReset: async (
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'action' is not null or undefined
      assertParamExists(
        'emailMessageControllerConvertUserForgottenPasswordReset',
        'action',
        action,
      );
      // verify required parameter 'userForgottenPasswordResetDto' is not null or undefined
      assertParamExists(
        'emailMessageControllerConvertUserForgottenPasswordReset',
        'userForgottenPasswordResetDto',
        userForgottenPasswordResetDto,
      );
      const localVarPath = `/email-message/user-forgotten-password-reset`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (action !== undefined) {
        localVarQueryParameter['action'] = action;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userForgottenPasswordResetDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerStats: async (
      options: any = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/email-message/stats`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserAccountCreatedDto} userAccountCreatedDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async emailMessageControllerConvert(
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userAccountCreatedDto: UserAccountCreatedDto,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.emailMessageControllerConvert(
          action,
          userAccountCreatedDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserForgottenPasswordResetDto} userForgottenPasswordResetDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async emailMessageControllerConvertUserForgottenPasswordReset(
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.emailMessageControllerConvertUserForgottenPasswordReset(
          action,
          userForgottenPasswordResetDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async emailMessageControllerStats(
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.emailMessageControllerStats(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserAccountCreatedDto} userAccountCreatedDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerConvert(
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userAccountCreatedDto: UserAccountCreatedDto,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .emailMessageControllerConvert(action, userAccountCreatedDto, options)
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
     * @param {UserForgottenPasswordResetDto} userForgottenPasswordResetDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerConvertUserForgottenPasswordReset(
      action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
      userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .emailMessageControllerConvertUserForgottenPasswordReset(
          action,
          userForgottenPasswordResetDto,
          options,
        )
        .then(request => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    emailMessageControllerStats(options?: any): AxiosPromise<void> {
      return localVarFp
        .emailMessageControllerStats(options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
  /**
   *
   * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
   * @param {UserAccountCreatedDto} userAccountCreatedDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  emailMessageControllerConvert(
    action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
    userAccountCreatedDto: UserAccountCreatedDto,
    options?: any,
  ): AxiosPromise<void>;

  /**
   *
   * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
   * @param {UserForgottenPasswordResetDto} userForgottenPasswordResetDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  emailMessageControllerConvertUserForgottenPasswordReset(
    action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
    userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
    options?: any,
  ): AxiosPromise<void>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApiInterface
   */
  emailMessageControllerStats(options?: any): AxiosPromise<void>;
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /**
   *
   * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
   * @param {UserAccountCreatedDto} userAccountCreatedDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public emailMessageControllerConvert(
    action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
    userAccountCreatedDto: UserAccountCreatedDto,
    options?: any,
  ) {
    return DefaultApiFp(this.configuration)
      .emailMessageControllerConvert(action, userAccountCreatedDto, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE'} action
   * @param {UserForgottenPasswordResetDto} userForgottenPasswordResetDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public emailMessageControllerConvertUserForgottenPasswordReset(
    action: 'VIEW_TEXT' | 'VIEW_HTML' | 'VIEW_TEMPLATE' | 'SEND' | 'QUEUE',
    userForgottenPasswordResetDto: UserForgottenPasswordResetDto,
    options?: any,
  ) {
    return DefaultApiFp(this.configuration)
      .emailMessageControllerConvertUserForgottenPasswordReset(
        action,
        userForgottenPasswordResetDto,
        options,
      )
      .then(request => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public emailMessageControllerStats(options?: any) {
    return DefaultApiFp(this.configuration)
      .emailMessageControllerStats(options)
      .then(request => request(this.axios, this.basePath));
  }
}
