import {
  Controller,
  Post,
  Body,
  VERSION_NEUTRAL,
  BadRequestException,
} from '@nestjs/common';
import { CharacterSheetRepository } from '../../models/character-sheet.repository';
import { CharacterSheet } from '../../models/character-sheet.schema';
import { CreateSpawnDto } from './create-spawn-dto';
import { PlaceService } from '../place/place.service';
import { SpawnService } from './spawn.service';
import { v4 } from 'uuid';

@Controller({ path: 'npcs', version: [VERSION_NEUTRAL, '1'] })
export class NpcController {
  constructor(
    private _characterSheetRepository: CharacterSheetRepository,
    private _placeService: PlaceService,
    private _spawnService: SpawnService,
  ) {}

  /**
   * Endpoint to dynamically autogenerated for in a given area
   */
  @Post()
  async create(@Body() createSpawnDto: CreateSpawnDto): Promise<any> {
    const place = await this._placeService.find(createSpawnDto.place);

    if (!place.spawnGuidelines) {
      return new BadRequestException('Spawn guidelines not found');
    }

    const createCharacterSheet = this._spawnService.calculateSpawn(
      place.spawnGuidelines,
    );

    const characterSheet = new CharacterSheet();
    if (createSpawnDto.id !== undefined) {
      characterSheet.id = createSpawnDto.id;
    }
    characterSheet.instanceId = createSpawnDto.instanceId;
    characterSheet.archetypeId = createCharacterSheet.archetypeId;

    return await this._characterSheetRepository.create(characterSheet);
  }
}
