#!/bin/sh
#
# This is an example Git hook for use with Rush.  To enable this hook, rename this file
# to "commit-msg" and then run "rush install", which will copy it from common/git-hooks
# to the .git/hooks folder.
#
# TO LEARN MORE ABOUT GIT HOOKS
#
# The Git documentation is here: https://git-scm.com/githooks
# Some helpful resources: https://githooks.com
#
# ABOUT THIS EXAMPLE
#
# The commit-msg hook is called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.  The hook is allowed to edit
# the commit message file.

# This example enforces that commit message should contain a minimum amount of
# description text.

node common/scripts/install-run-rush.js commitlint --edit $1
exit 1

COMMIT_MESSAGE="$1"

echo "$COMMIT_MESSAGE"

if [ $(cat $COMMIT_MESSAGE | wc -w) -lt 3 ]; then
  echo ""
  echo "Invalid commit message: The message must contain at least 3 words."
  exit 1
fi

exit 1

# Run commitlint with the commit message as an argument
echo "${COMMIT_MESSAGE}" | commitlint

if [ $? -ne 0 ]; then
  echo "commitlint failed. Exiting..."
  exit 1
else
  echo "commitlint passed."
fi

# enforce DCO https://wiki.linuxfoundation.org/dco
NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
  echo "empty git config user.name"
  exit 1
fi

if [ -z "$EMAIL" ]; then
  echo "empty git config user.email"
  exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
  "Signed-off-by: $NAME <$EMAIL>" \
  --in-place "$1"
