import { kebabCase, truncate } from 'lodash';

export abstract class BaseMessageDto {
  /**
   * Get autogenerated SNS topic name
   * The name is prefixed by STAGE and contains the class name.
   * {@link https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-messages.html}
   * {@link https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-queues.html}
   */
  get topicName(): string {
    const stage = (process.env.STAGE ?? 'default').toLowerCase();
    const className = this.constructor.name;
    const classNameKebabCase = kebabCase(className);
    let topicName = truncate(`${stage}-${classNameKebabCase}`, {
      length: 256 - '-topic'.length,
      omission: '-topic',
      separator: '-',
    });
    if (!/-topic$/.test(topicName)) {
      topicName += '-topic';
    }

    return topicName;
  }

  /**
   * Get auto generated SQS queue name
   * The name is prefixed by STAGE and APP_NAME followed by the message name with a queue suffix
   * {@link https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-messages.html}
   * {@link https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-queues.html}
   */
  get queueName(): string {
    const stage = (process.env.STAGE ?? 'default').toLowerCase();
    const appName = (process.env.APP_NAME ?? 'undefined').toLowerCase();
    const className = this.constructor.name;
    const classNameKebabCase = kebabCase(className);
    let queueName = truncate(`${stage}-${appName}-${classNameKebabCase}`, {
      length: 80 - '-queue'.length,
      omission: '-queue',
      separator: '-',
    });
    if (!/-queue$/.test(queueName)) {
      queueName += '-queue';
    }

    return queueName;
  }

  /**
   * Get auto generated topicArn
   * {@link https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html}
   * {@link https://docs.aws.amazon.com/IAM/latest/APIReference/API_User.html}
   */
  get topicArn(): string {
    const region = process.env.AWS_REGION;
    const account = process.env.AWS_ACCOUNT;
    const { topicName } = this;

    return `arn:aws:sns:${region}:${account}:${topicName}`;
  }
}
