/* tslint:disable */
/* eslint-disable */
/**
 * @org-packages/luck-by-dice
 * An API for simulating dice rolls and from dice notations with luck modifiers
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} notation The dice notation
         * @param {number} luck The luck of the character performing action
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rollControllerFind: async (notation: string, luck: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'notation' is not null or undefined
            assertParamExists('rollControllerFind', 'notation', notation)
            // verify required parameter 'luck' is not null or undefined
            assertParamExists('rollControllerFind', 'luck', luck)
            const localVarPath = `/roll/notation/{notation}/luck/{luck}`
                .replace(`{${"notation"}}`, encodeURIComponent(String(notation)))
                .replace(`{${"luck"}}`, encodeURIComponent(String(luck)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} notation The dice notation
         * @param {number} luck The luck of the character performing action
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rollControllerFind(notation: string, luck: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rollControllerFind(notation, luck, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {string} notation The dice notation
         * @param {number} luck The luck of the character performing action
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rollControllerFind(notation: string, luck: number, options?: any): AxiosPromise<void> {
            return localVarFp.rollControllerFind(notation, luck, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * 
     * @param {string} notation The dice notation
     * @param {number} luck The luck of the character performing action
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    rollControllerFind(notation: string, luck: number, options?: AxiosRequestConfig): AxiosPromise<void>;

}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * 
     * @param {string} notation The dice notation
     * @param {number} luck The luck of the character performing action
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rollControllerFind(notation: string, luck: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rollControllerFind(notation, luck, options).then((request) => request(this.axios, this.basePath));
    }
}


