import React from 'react';
import { Meta } from '@storybook/react';
import { IsometricCanvas, IsometricCanvasProps } from '../../src/main';

export default {
  title: 'Game Assets/HUD/IsometricCanvas',
  component: IsometricCanvas,
} as Meta<typeof IsometricCanvas>;

export const TrainCar = (args: IsometricCanvasProps) => (
  <IsometricCanvas {...args} />
);

TrainCar.args = {
  spriteMapRegistry: {
    f: '/game-assets/fadewall-1x1.png',
    t: '/game-assets/tileset-4x4.png',
    b: '/game-assets/barrel-1x1.png',
    d: '/game-assets/door-1x1.png',
    w: '/game-assets/trainwall-8x1.png',
    n: '/game-assets/nightstand-4x3.png',
    s: '/game-assets/seat-4x1.png',
    os: '/game-assets/safe-4x1.png',
    ol: '/game-assets/switches-4x1.png',
  },
  grid: [
    [
      [
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w1',
        'w1',
      ],
      [
        'w1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'w1',
      ],

      [
        'w1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'w1',
      ],
      [
        'f1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'f1',
      ],
      [
        'w1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'f1',
      ],
      [
        'w1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'w1',
      ],
      [
        'w1',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        't2',
        'w1',
      ],

      [
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w2',
        'w1',
        'w1',
        'w1',
      ],
    ],
    [
      ['0'],
      [
        '0',
        'os2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
      ],
      [
        '0',
        '0',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
      ],
      ['d1'],
      ['0'],
      [
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
      ],
      [
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
        '0',
        's2',
        '0',
        's4',
        's2',
      ],
    ],
  ],
  cameraPosition: { x: 0, y: 0, z: 0 },
} as IsometricCanvasProps;

export const Room = (args: IsometricCanvasProps) => (
  <IsometricCanvas {...args} />
);

Room.args = {
  spriteMapRegistry: {
    f: '/game-assets/fadewall-1x1.png',
    t: '/game-assets/tileset-4x4.png',
    b: '/game-assets/barrel-1x1.png',
    d: '/game-assets/door-1x1.png',
    w: '/game-assets/trainwall-8x1.png',
    n: '/game-assets/nightstand-4x3.png',
  },
  grid: [
    [
      ['w1', 'w1', 'w1', 'w4', 'w1', 'f1', 'w1', 'w1'],
      ['w1', 't2', 't2', 't2', 't2', 't2', 't2', 'w1'],
      ['w1', 't2', 't2', 't2', 't2', 't2', 't2', 'w1'],
      ['w1', 't2', 't2', 't2', 't2', 't2', 't2', 't2'],
      ['w1', 't2', 't2', 't2', 't2', 't2', 't2', 'w1'],
      ['w5', 't2', 't2', 't2', 't2', 't2', 't2', 'w1'],
      ['w1', 't2', 't2', 't2', 't2', 't2', 't2', 'w1'],
      ['w1', 'w1', 'w1', 'w1', 't2', 'w1', 'w1', 'w1'],
    ],
    [
      ['0', '0', '0', '0', '0', 'd1', '0'],
      ['0', '0', '0', '0', '0', '0', 'b1'],
      ['0', 't10', 't9', 't9'],
      ['0', 't10', 't9', 't9'],
      ['0'],
      ['0', 'n10'],
      ['0'],
    ],
  ],
  cameraPosition: { x: 0, y: 0, z: 0 },
} as IsometricCanvasProps;
