/* tslint:disable */
/* eslint-disable */
/**
 * @cats-cradle/luck-by-dice
 * An API Simulating dice rolls that can be effected by luck from dice notation
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
