/* tslint:disable */
/* eslint-disable */
/**
 * @cats-cradles/luck-by-dice
 * An API for simulating dice rolls and luck from dice notation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
