export enum Effect {
  MILD_WIND = 'MILD_WIND',
  WIND = 'WIND',
  HEAVY_WIND = 'HEAVY_WIND',

  MILD_DUST_STORM = 'MILD_DUST_STORM',
  DUST_STORM = 'DUST_STORM',
  HEAVY_DUST_STORM = 'HEAVY_DUST_STORM',

  MILD_RAIN = 'MILD_RAIN',
  RAIN = 'RAIN',
  HEAVY_RAIN = 'HEAVY_RAIN',

  MILD_ICE_STORM = 'MILD_ICE_STORM',
  ICE_STORM = 'ICE_STORM',
  HEAVY_ICE_STORM = 'HEAVY_ICE_STORM',

  MILD_SNOW = 'MILD_SNOW',
  SNOW = 'SNOW',
  HEAVY_SNOW = 'HEAVY_SNOW',

  HURRICANE = 'HURRICANE',
  TORNADOES = 'TORNADOES',
  TYPHOONS = 'TYPHOONS',
}
