export enum HappinessType {
  EXUBERANT = 'EXUBERANT',
  JOYFUL = 'JOYFUL',
  VERY_HAPPY = 'VERY HAPPY',
  HAPPY = 'HAPPY',
  SATISFIED = 'SATISFIED',
  CONTENT = 'CONTENT',
  UNHAPPY = 'UNHAPPY',
  SAD = 'SAD',
  VERY_SAD = 'VERY_SAD',
  DEPRESSED = 'DEPRESSED',
  HOPELESS = 'HOPELESS',
}
